---
title: "Applied Statistical Analysis I"
author: "Jeffrey Ziegler, Department of Political Science, Trinity College Dublin"
date: "2021-2022"
documentclass: book
site: bookdown::bookdown_site
bibliography: bibliography.bib
---

# Syllabus {-}

## Module description {-}

The first course in the statistics sequence introduces the linear regression model as a fundamental tool in political analysis. The course underscores applications with the kind of data that are likely to be encountered in applied research. We will cover the assumptions that underlie the linear regression model, issues of estimation and inference, and methods used to diagnose and correct gross violations of linear regression assumptions, mostly relying on R to carry out computations. My expectation is that at the end of the semester you will be savvy readers of published research and tasteful users of linear models; especially, I hope that you will understand the role that different assumptions play in the construction of linear models.

## Readings {-}

This is a list of interesting and pertinent books that will be used during the course. You need to consult them occasionally, but you do not need to purchase them. I will provide the assigned readings in PDF format.

- Angresti, Alan and Barbara Finlay (2009). Statistical Methods for the Social Sciences. Fourth Edition. 
- Chatterjee, Samprit and Ali S. Hadi (2012). Regression Analysis by Example. 5th edition.
- Cunningham, Scott (2020). Causal Inference: The Mixtape. 1st Edition.
- Fox, John (2015). Applied Regression Analysis and Generalized Linear Models. 3rd edition.
- Hosmer, David W., Stanley Lemeshow, and Rodney X. Sturdivant (2013). Applied Logistic Regression. 3rd edition.
- Imai, Kosuke (2017). Quantitative Social Science: Introduction. 1st edition.
- James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani (2013). An Introduction to Statistical Learning with Applications in R. 1st edition.
- Kmenta, Jan (1986). Elements of Econometrics. University of Michigan.
